### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by wwitzel3** [JessaWitzel/retirement_goal_calc#1]
Let's call out what methods from the YNAB API we will be using in the README.
We can also place our compound interest formula in the readme.
We can create a narrative documentation, something like:

```The retirement_goal_calc determines how much per-month you will need to save, to meet your monthly dividend goal. To do this, we will use information from the YNAB API and information you enter, such as target retirement date and estimated rate of return.```

**Comment by JessaWitzel** [comment]
update it with markdown

**Comment by wwitzel3** [comment]
We probably want to call out how we plan to calculate project should their total investments be spread across 3 accounts.

**Comment by JessaWitzel** [comment]
1a31674 Updated with more specific API calls.
