### ISSUE TITLE
Determine which parts of the YNAB we need.

### ISSUE THREAD

**Issue by wwitzel3** [JessaWitzel/retirement_goal_calc#3]
We want to collect all of the accounts needed to perform our retirement goal calculation.

To do that, we will need to fetch all of the accounts, show them to the user and have them include them as investments to track.

We will want to look at https://api.youneedabudget.com to determine what endpoints will contain the data we need. This will also help us create our mock data for #2

**Comment by JessaWitzel** [comment]
Get user input for the names of their mortgage budget and their investment budgets. Use GET /budgets/{budget_id}

**Comment by wwitzel3** [comment]
We will probably want to show them a list of budgets: https://api.youneedabudget.com/v1#/Budgets/getBudgets

They will select the budget that contains their accounts and the we will make a request to: https://api.youneedabudget.com/v1#/Accounts/getAccounts

Then we can show them a list of their accounts and they can mark/flag their mortgage account(s) and their investment account(s).

Once we know the accounts we can fetch the balance details from: https://api.youneedabudget.com/v1#/Accounts/getAccountById

**Comment by JessaWitzel** [comment]
Updated Readme.md with more specific API calls. 1a31674
